# .github/workflows/reusable-build-job.yml
name: Reusable - Universal Build Job
on:
  workflow_call:
    inputs:
      project_key:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      do_release:
        required: true
        type: string
      is_prerelease:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 核心环境变量，构建脚本会依赖它们
      CCACHE_DIR: "${{ github.workspace }}/.ccache"
      PROJECT_KEY: ${{ inputs.project_key }}
      BRANCH_NAME: ${{ inputs.branch_name }}
      DO_RELEASE: ${{ inputs.do_release }}
      IS_PRERELEASE_INPUT: ${{ inputs.is_prerelease }}
    steps:
      - uses: actions/checkout@v4

      - name: 安装依赖项
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git libncurses5-dev bc bison flex libssl-dev p7zip-full lz4 cpio curl libelf-dev dwarves ccache jq lld
      
      - name: 解析项目配置
        id: config
        run: |
          CONFIG_JSON=$(cat ${{ github.workspace }}/configs/projects.json | jq -r --arg PKEY "$PROJECT_KEY" '.[$PKEY]')
          if [ -z "$CONFIG_JSON" ] || [ "$CONFIG_JSON" == "null" ]; then echo "错误: 未找到项目 '$PROJECT_KEY' 的配置。"; exit 1; fi

          echo "PROJECT_REPO=$(echo $CONFIG_JSON | jq -r .repo)" >> $GITHUB_ENV
          echo "PROJECT_DEFCONFIG=$(echo $CONFIG_JSON | jq -r .defconfig)" >> $GITHUB_ENV
          echo "PROJECT_LOCALVERSION_BASE=$(echo $CONFIG_JSON | jq -r .localversion_base)" >> $GITHUB_ENV
          echo "PROJECT_LTO=$(echo $CONFIG_JSON | jq -r .lto)" >> $GITHUB_ENV
          echo "PROJECT_TOOLCHAIN_URLS=$(echo $CONFIG_JSON | jq -c .toolchain_urls)" >> $GITHUB_ENV
          echo "PROJECT_TOOLCHAIN_PATH_PREFIX=$(echo $CONFIG_JSON | jq -r .toolchain_path_prefix)" >> $GITHUB_ENV
          echo "PROJECT_TOOLCHAIN_PATH_EXPORTS=$(echo $CONFIG_JSON | jq -c .toolchain_path_exports)" >> $GITHUB_ENV
          ANYKERNEL_REPO_URL=$(echo $CONFIG_JSON | jq -r .anykernel_repo)
          echo "PROJECT_ANYKERNEL_REPO=${ANYKERNEL_REPO_URL}" >> $GITHUB_ENV
          ANYKERNEL_REPO_SLUG=$(echo "$ANYKERNEL_REPO_URL" | sed 's|https://github.com/||' | sed 's|\.git$||')
          echo "PROJECT_ANYKERNEL_REPO_SLUG=${ANYKERNEL_REPO_SLUG}" >> $GITHUB_ENV
          echo "PROJECT_ANYKERNEL_BRANCH=$(echo $CONFIG_JSON | jq -r .anykernel_branch)" >> $GITHUB_ENV
          echo "PROJECT_ZIP_NAME_PREFIX=$(echo $CONFIG_JSON | jq -r .zip_name_prefix)" >> $GITHUB_ENV
          echo "PROJECT_VERSION_METHOD=$(echo $CONFIG_JSON | jq -r '.version_method // "param"')" >> $GITHUB_ENV
          echo "PROJECT_EXTRA_HOST_ENV=$(echo $CONFIG_JSON | jq -r '.extra_host_env // "false"')" >> $GITHUB_ENV
          echo "PROJECT_DISABLE_SECURITY=$(echo $CONFIG_JSON | jq -c '.disable_security // []')" >> $GITHUB_ENV

      - name: Checkout 内核源码仓库
        uses: actions/checkout@v4
        with: {repository: "${{ env.PROJECT_REPO }}", ref: "${{ env.BRANCH_NAME }}", path: kernel_source, submodules: 'recursive'}
      
      - name: 下载并解压工具链
        working-directory: kernel_source
        run: |
          URLS=$(echo '${{ env.PROJECT_TOOLCHAIN_URLS }}' | jq -r '.[]')
          PART_FILES=""
          i=0
          for url in $URLS; do
            part_file="toolchain.part$i"
            wget -O "$part_file" "$url"
            PART_FILES="$PART_FILES $part_file"
            i=$((i+1))
          done
          cat $PART_FILES > toolchain.tar.gz
          mkdir -p ./toolchain && tar -xzvf toolchain.tar.gz -C ./toolchain/
          rm $PART_FILES toolchain.tar.gz
          echo "--- 为工具链二进制文件设置可执行权限 ---"
          find ./toolchain -type f -path "*/bin/*" -exec chmod +x {} \;
      
      - name: Checkout AnyKernel3 仓库
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PROJECT_ANYKERNEL_REPO_SLUG }}
          ref: ${{ env.PROJECT_ANYKERNEL_BRANCH }}
          path: anykernel_repo
          fetch-depth: 1

      - name: 设置 ccache 环境并恢复缓存
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          # key 使用 run_id 保证每次运行都唯一, 从而确保任务结束后总是会保存新缓存
          key: ${{ runner.os }}-ccache-${{ env.PROJECT_KEY }}-${{ github.run_id }}
          # restore-keys 使用项目名称作为前缀, 会拉取该项目最新的可用缓存进行恢复
          restore-keys: |
            ${{ runner.os }}-ccache-${{ env.PROJECT_KEY }}-

      - name: 根据分支设置 KernelSU
        working-directory: ./kernel_source
        run: |
          if [[ "${{ env.BRANCH_NAME }}" == "sukisuultra" ]]; then
            if [[ "${{ env.PROJECT_KEY }}" == "z3_sm8350" ]]; then
              echo "--- 检测到 z3_sm8350 的 sukisuultra 分支, 使用 susfs-legacy 版本的 SukiSU ---"
              curl -LSs "https://raw.githubusercontent.com/vc-teahouse/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-legacy
            else
              echo "--- 使用标准的 SukiSU-Ultra ---"
              curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s susfs-main
            fi
          elif [[ "${{ env.BRANCH_NAME }}" == "mksu" ]]; then
            curl -LSs "https://raw.githubusercontent.com/5ec1cff/KernelSU/main/kernel/setup.sh" | bash -
          elif [[ "${{ env.BRANCH_NAME }}" == "ksu" ]]; then
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
          fi

      - name: 补充 ccache 环境变量
        run: |
          echo "CCACHE_BASEDIR=${{ github.workspace }}/kernel_source" >> $GITHUB_ENV
          echo "CCACHE_SLOPPINESS=time_macros" >> $GITHUB_ENV

      - name: 运行通用构建脚本
        env: {GH_TOKEN: "${{ secrets.GH_TOKEN }}"}
        run: |
          cp scripts/build.sh ./kernel_source/
          cd ./kernel_source
          chmod +x ./build.sh
          ./build.sh
      
      - name: 上传构建产物
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ env.PROJECT_KEY }}-${{ env.BRANCH_NAME }}-${{ github.run_id }}
          path: |
            kernel_source/out/*.zip
            kernel_source/kernel_build_log.txt
          retention-days: 7
